blueprint:
  name: Sincronizar Switches ou Luzes (Sem Loop)
  description: >
    Sincroniza múltiplos switches ou lights no Home Assistant sem loops. Quando um for alterado, todos os outros são atualizados para o mesmo estado (on ou off).
  domain: automation
  input:
    switches:
      name: Entidades a sincronizar
      description: Selecione os switches ou lights que deseja manter sincronizados.
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

trigger:
  - platform: state
    entity_id: !input switches
    to: "on"
  - platform: state
    entity_id: !input switches
    to: "off"

condition:
  - condition: template
    value_template: >
      {% set other = expand(trigger.entity_id, expand(!input switches) | map(attribute='entity_id') | reject('equalto', trigger.entity_id) | list) %}
      {% if trigger.to_state.state in ['on', 'off'] %}
        {{ other | selectattr('state', 'ne', trigger.to_state.state) | list | count > 0 }}
      {% else %}
        false
      {% endif %}

action:
  - service: >
      {% if trigger.to_state.state == 'on' %}
        homeassistant.turn_on
      {% else %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id: !input switches

mode: queued
max: 5
